[book]
multilingual = false
src = "guide"

[build]
build-dir = "build/guide"
create-missing = false

[output.html]
additional-css = ["guide/css/custom.css"]
edit-url-template = "https://github.com/projectfluent/fluent/edit/master/{path}"
git-repository-url = "https://github.com/projectfluent/fluent/"
no-section-label = true
